# Generated by Django 4.2.2 on 2023-07-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
