# Generated by Django 4.2.2 on 2023-07-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria_cliente_inventario_usuario_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
