# Generated by Django 4.2.2 on 2023-07-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
