# Generated by Django 4.2.2 on 2023-07-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
